# -*- coding: utf-8 -*-

from django.conf.urls import patterns

urlpatterns = patterns('home_application.views',
    (r'^$', 'index'),
    (r'^header/$', 'header'),
    (r'^menu/$', 'menu'),
    (r'^apply/$', 'apply'),
    (r'^applylist/$', 'applylist'),
    (r'^apply_edit/$', 'apply_edit'),
    (r'^apply_info/$', 'apply_info'),
    (r'^deploy_info/$', 'deploy_info'),
    (r'^apply_del/$', 'apply_del'),
    (r'^testlist_xk/$', 'testlist_xk'),
    (r'^test_pass_xk/$', 'test_pass_xk'),
    (r'^test_back_xk/$', 'test_back_xk'),
    (r'^testlist_sc/$', 'testlist_sc'),
    (r'^test_pass_sc/$', 'test_pass_sc'),
    (r'^test_back_sc/$', 'test_back_sc'),
    (r'^rollbacklist/$', 'rollbacklist'),
    (r'^returnedlist/$', 'returnedlist'),
    (r'^successlist/$', 'successlist'),
    (r'^review/$', 'review'),
    (r'^review_pass/$', 'review_pass'),
    (r'^review_back/$', 'review_back'),
    (r'^review_rollback/$', 'review_rollback'),
    (r'^package/$', 'package'),
    (r'^newapp/$', 'newapp'),
    (r'^applist/$', 'applist'),
    (r'^app_edit/$', 'app_edit'),
    (r'^app_del/$', 'app_del'),
    (r'^appoperation/$', 'appoperation'),
    (r'^monitor/$', 'monitor'),
    (r'^dev-guide/$', 'dev_guide'),
    (r'^contactus/$', 'contactus'),
    (r'^urllist/$', 'urllist'),
    (r'^elk/$', 'elk'),
    (r'^logstatus/$', 'logstatus'),
    (r'^operation/$', 'operation'),
)
