# -*- coding: utf-8 -*-

from django.conf.urls import patterns

urlpatterns = patterns('home_application.views',
    (r'^$', 'index'),
    (r'^header/$', 'header'),
    (r'^menu/$', 'menu'),
    (r'^apply/$', 'apply'),
    (r'^applylist/$', 'applylist'),
    (r'^apply_edit/$', 'apply_edit'),
    (r'^apply_del/$', 'apply_del'),
    (r'^testlist/$', 'testlist'),
    (r'^test_pass/$', 'test_pass'),
    (r'^test_back/$', 'test_back'),
    (r'^rollbacklist/$', 'rollbacklist'),
    (r'^returnedlist/$', 'returnedlist'),
    (r'^review/$', 'review'),
    (r'^review_pass/$', 'review_pass'),
    (r'^review_back/$', 'review_back'),
    (r'^package/$', 'package'),
    (r'^newapp/$', 'newapp'),
    (r'^applist/$', 'applist'),
    (r'^app_edit/$', 'app_edit'),
    (r'^app_del/$', 'app_del'),
    (r'^appoperation/$', 'appoperation'),
    (r'^monitor/$', 'monitor'),
    (r'^dev-guide/$', 'dev_guide'),
    (r'^contactus/$', 'contactus'),
    (r'^urllist/$', 'urllist'),
    (r'^elk/$', 'elk'),
    (r'^logstatus/$', 'logstatus'),
    # (r'^get_json/$', 'get_json'),
)
